### ISSUE TITLE
Typo for Zero in /etc/config/arduino?

### ISSUE THREAD

**Issue by sandeepmistry** [arduino/openwrt-arduino-packages#1]
I think there is a typo in [`/etc/config/arduino`](https://github.com/arduino/openwrt-arduino-packages/blob/for-15.05/yun-conf/files/etc/config/arduino):

```
option arduino_sam_zero 'run-bossac -i -d --port=ttyATH0 -U false -e -w -v /tmp/sketch.hex -R'
```

Should `arduino_sam_zero` be `arduino_samd_zero` (`d` is missing in `samd`)?

**Comment by facchinm** [comment]
Hi @sandeepmistry , that's correct, but that label is referenced in YunPanel (https://github.com/arduino/YunWebUI/blob/79aaf8a9cd956c2de89100215619845ef81625f4/usr/lib/lua/luci/view/arduino/homepage.htm#L164) and that commit was added long before deciding the `samd` name :smile: 
A future revision should correct both these issues

**Comment by nsmith1024** [comment]
Does anybody know where i can find the official Openwrt OS source code for Arduino YUN rev-2 board? 

Im not talking about the packages or anything else, just the main Linux OS source code for OpenWRT for the Arduino YUN rev-2 board so I can modify the OpenWRT linux kernel code itself for the Arduino rev-2 board so i can make a new custom build using make menuconfig
